### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by JVTEAM** [LordofBone/The-Nvidianator#2]
Having an index error...

Processing objects and looking for faces
./my-recognition: symbol lookup error: ./my-recognition: undefined symbol: _Z13loadImageRGBAPKcPP6float4S3_PiS4_
Traceback (most recent call last):
  File "nvmain.py", line 71, in <module>
    topPrediction, topPredictionConfidence, humanid, confidence = vision_analysis.imageAnalyse(class_names, device, model_trained)
  File "/home/***/Downloads/The-Nvidianator/vision_analysis.py", line 51, in imageAnalyse
    topPrediction, topPredictionConfidence = object_infer.infer_object()
  File "/home/***/Downloads/The-Nvidianator/object_infer.py", line 17, in infer_object
    topPredictionSplit = str(out.split("recognized as ")[1])
IndexError: list index out of range

**Comment by JVTEAM** [comment]
Figured out I had to make my out ./my-recognition file in order for this to work for me.
